apiVersion: v1
kind: Namespace
metadata:
  name: httproute-viewer
---
apiVersion: v1
kind: Service
metadata:
  name: httproute-viewer
  namespace: httproute-viewer
spec:
  selector:
    app: httproute-viewer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httproute-viewer
  namespace: httproute-viewer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: httproute-viewer
rules:
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["httproutes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: httproute-viewer
subjects:
- kind: ServiceAccount
  name: httproute-viewer
  namespace: httproute-viewer
roleRef:
  kind: ClusterRole
  name: httproute-viewer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httproute-viewer
  namespace: httproute-viewer
  labels:
    app: httproute-viewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httproute-viewer
  template:
    metadata:
      labels:
        app: httproute-viewer
    spec:
      serviceAccountName: httproute-viewer
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: httproute-viewer
        image: ghcr.io/simonfelding/httproute-viewer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
          readOnlyRootFilesystem: true
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
