name: Build and Push Docker Image to GHCR

# Run this workflow on every push to the main branch
on:
  push:
    branches: [ main ]

# A GITHUB_TOKEN is automatically created by Actions.
# We need to give it permissions to write to the package registry.
permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          # The GITHUB_TOKEN secret is automatically available in actions.
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          # Build for both AMD64 and ARM64
          platforms: linux/amd64,linux/arm64
          push: true
          # Tags the image with 'latest' and the git commit hash
          # The image will be pushed to ghcr.io/YOUR-USERNAME/YOUR-REPO
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}